EXTENSION = crud_generator
DATA = sql/crud_generator--1.0.sql
PGFILEDESC = "crud_generator - generador automatico de procedimientos CRUD"

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
