-- tests/fixtures/02_schema.sql
-- Fase 0 — Laboratorio de 6 tablas (Joseph). Owner: crud_admin.
-- Tablas 1-5: uso libre en pruebas. Tabla 6 (tabla_virgen): RESERVADA, no usar.
-- Requiere: 01_roles.sql

SET ROLE crud_admin;

-- Tabla 1 — PK simple
DROP TABLE IF EXISTS lab.detalle_factura;
DROP TABLE IF EXISTS lab.producto;
CREATE TABLE lab.producto (
  id_producto integer PRIMARY KEY,
  nombre      text NOT NULL,
  precio      numeric(10,2) NOT NULL CHECK (precio >= 0)
);

-- Tabla 2 — PK compuesta
CREATE TABLE lab.detalle_factura (
  id_factura integer NOT NULL,
  id_producto integer NOT NULL REFERENCES lab.producto(id_producto),
  cantidad   integer NOT NULL CHECK (cantidad > 0),
  PRIMARY KEY (id_factura, id_producto)
);

-- Tabla 3 — autogeneración (IDENTITY + DEFAULT)
DROP TABLE IF EXISTS lab.ticket;
CREATE TABLE lab.ticket (
  id_ticket integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  codigo    text NOT NULL DEFAULT 'SIN-CODIGO',
  creado_en timestamptz NOT NULL DEFAULT now()
);

-- Tabla 4 — sin PK (caso límite ADR-009)
DROP TABLE IF EXISTS lab.bitacora;
CREATE TABLE lab.bitacora (
  id_sesion integer,
  mensaje   text,
  creado_en timestamptz NOT NULL DEFAULT now()
);

-- Tabla 5 — tipos variados + nombres que exigen quoting + DEFAULT
DROP TABLE IF EXISTS lab.catalogo_especial;
CREATE TABLE lab.catalogo_especial (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre Ítem" text NOT NULL,
  "precio$"    numeric(12,2) NOT NULL DEFAULT 0,
  activo       boolean NOT NULL DEFAULT true,
  datos        jsonb NOT NULL DEFAULT '{}'::jsonb,
  fecha        date NOT NULL DEFAULT CURRENT_DATE
);

-- Tabla 6 — VIRGEN: reservada para la prueba final de tabla desconocida.
-- REGLA: crearla vacía y NO tocarla en Fase 0 (ni SELECT de diseño, ni fixtures,
-- ni grants específicos más allá del default). Su DDL real se define con el equipo
-- cuando se acuerde el protocolo "tabla del profesor".
DROP TABLE IF EXISTS lab.tabla_virgen;
CREATE TABLE lab.tabla_virgen (
  id   integer PRIMARY KEY,
  nota text
);
COMMENT ON TABLE lab.tabla_virgen IS
  'RESERVADA Fase 0: no usar en pruebas. Simula la tabla desconocida del profesor.';

RESET ROLE;
